apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_6c2de3b51e325bc98a35fccf44ac3ee8.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_6c2de3b51e325bc98a35fccf44ac3ee8.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.helm_service_account_6c2de3b51e325bc98a35fccf44ac3ee8.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_6c2de3b51e325bc98a35fccf44ac3ee8.automount }}
