{{- if .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.workload_kind }}
    name: {{ .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.workload_name }}
  minReplicas: {{ .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_5c68b57700f554e7b50b3647c6652c1d.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}