name: Deploy Spring Boot App to Kubernetes with RDS

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: your-cluster-name
  NAMESPACE: default
  HELM_RELEASE_NAME: petclinic-release
  CHART_PATH: ./helm-chart-path

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production  #  This enables approval
      url: https://your-app-url.com  # optional

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Get EKS credentials
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

# This stage waits for manual approval
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply tfplan

      - name: Get RDS Endpoint
        working-directory: ./terraform
        run: |
          echo "RDS_ENDPOINT=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV

      - name: Deploy with Helm
        run: |
          helm upgrade --install $HELM_RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE \
            --set db.rds_endpoint=$RDS_ENDPOINT
